[build-system]
requires = ["wheel",
            "setuptools >= 30.3.0",
            "cmake >= 3.12",
            "pybind11[global] >= 2.6.0"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py3

[testenv]
deps = pytest
       numpy
       pybind11
changedir = python/tests
commands = pytest
"""