name: Build Python Wheels

on:
  # allow manual runs
  workflow_dispatch:
  # run when we tag a release
  release:
    types:
      - "created"

env:
  BUILD_TYPE: Release

jobs:
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: python -m pip install cibuildwheel==2.7.0

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest, GCC",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
           
      - name: Install Python dependencies
        run: python -m pip install cibuildwheel==2.7.0
        
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_BUILD: python --version
          CIBW_BUILD_FRONTEND: "build"
          CIBW_SKIP: "*-win32"
          CIBW_BUILD: "cp38-*manylinux*64"
          CIBW_ARCHS_MACOS: "x86_64 universal2"
          CIBW_TEST_COMMAND: 'python -m pytest {package}/python/tests'

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
