name: Build Python Wheels

on:
  # allow manual runs
  workflow_dispatch:
  # run when we tag a release
  release:
    types:
      - "created"

env:
  BUILD_TYPE: Release

jobs:
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel numpy tox pytest build

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "MacOS Latest (Apple Silicon)",
            os: macos-latest,
            cibw-arch: macosx_arm64
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Qemu when building arm
        if: ${{ matrix.config.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.7.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_PRERELEASE_PYTHONS: True # enable Python 3.11
          CIBW_SKIP: "*-win32 *musllinux*"
          CIBW_BUILD: "cp311*-${{ matrix.config.cibw-arch }}"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_ARCHS_LINUX: ${{ matrix.config.arch }}

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
